apiVersion: v2
name: keycloakx-chart
description: Keycloak with Zero Trust configuration using keycloakx
type: application
version: 1.0.0
appVersion: "26.0.7"

dependencies:
  - name: keycloakx
    version: "2.4.4"
    repository: https://codecentric.github.io/helm-charts
